---
- name: Install memcached
  yum:
    name: memcached
    state: present

- name: Copy Memcached configuration
  template:
    src: memcached.conf.j2
    dest: "{{ memcached_config_file }}"
    owner: root
    group: root
    mode: 0644
  notify: Restart memcached

- name: Ensure Memcached is started and set to run on startup
  service:
    name: memcached
    state: started
    enabled: yes

- name: Listen on memcached port (firewalld)
  firewalld:
    port: "{{ memcached_port }}/tcp"
    state: enabled
    immediate: true
    permanent: true
  when: ansible_distribution_file_variety == 'RedHat' and ansible_distribution_major_version == '7' and memcached_open_firewall
